name: Build on release
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - run: dotnet publish -c release -r win10-x64 -o /tmp/solidPancake --sc

    - name: Upload Linux binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/solidPancake/*.exe
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
